definitions:
  model.FullProduct:
    properties:
      avg_price:
        type: number
      barcode_image:
        type: string
      brand_name:
        type: string
      brand_picture:
        type: string
      created_at:
        type: string
      description:
        type: string
      gross_weight:
        type: number
      gtin:
        type: integer
      height:
        type: number
      id:
        type: integer
      length:
        type: number
      max_price:
        type: number
      min_price:
        type: number
      ncm:
        $ref: '#/definitions/model.NCM'
      ncm_code:
        type: string
      net_weight:
        type: number
      origin:
        type: string
      price:
        type: string
      release_date:
        type: string
      updated_at:
        type: string
      width:
        type: number
    type: object
  model.NCM:
    properties:
      code:
        type: string
      description:
        type: string
      ex:
        type: string
      full_description:
        type: string
    type: object
info:
  contact:
    name: Meditrack Team
    url: localhost:3333
  description: API para consulta de itens por codigo de barras.
  title: Meditrack API
  version: "1.0"
paths:
  /v1/ncm:
    get:
      description: Retorna todos os NCMs cadastrados.
      operationId: GetAllNCM
      produces:
      - application/json
      responses:
        "200":
          description: Requisição bem sucedida.
          schema:
            $ref: '#/definitions/model.NCM'
        "500":
          description: Erro interno.
          schema:
            type: string
      tags:
      - Nomenclatura Comum do Mercosul
    post:
      consumes:
      - application/json
      description: Cria um novo NCM.
      operationId: CreateNCM
      parameters:
      - description: NCM a ser criado
        in: body
        name: ncm
        required: true
        schema:
          $ref: '#/definitions/model.NCM'
      produces:
      - application/json
      responses:
        "201":
          description: Requisição bem sucedida.
          schema:
            $ref: '#/definitions/model.NCM'
        "400":
          description: Requisição inválida.
          schema:
            type: string
        "500":
          description: Erro interno.
          schema:
            type: string
      tags:
      - Nomenclatura Comum do Mercosul
  /v1/ncm/{code}:
    get:
      description: Retorna um NCM com base no código informado.
      operationId: GetNCMByCode
      parameters:
      - description: Código do NCM
        in: path
        name: code
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Requisição bem sucedida.
          schema:
            $ref: '#/definitions/model.NCM'
        "404":
          description: NCM não encontrado.
          schema:
            type: string
        "500":
          description: Erro interno.
          schema:
            type: string
      tags:
      - Nomenclatura Comum do Mercosul
  /v1/product:
    get:
      description: Retorna todos os itens cadastrados.
      operationId: GetAllProducts
      produces:
      - application/json
      responses:
        "200":
          description: Requisição bem sucedida.
          schema:
            $ref: '#/definitions/model.FullProduct'
        "500":
          description: Erro interno.
          schema:
            type: string
      tags:
      - Produtos
    post:
      consumes:
      - application/json
      description: Cria um novo item.
      operationId: CreateProduct
      parameters:
      - description: Item a ser criado.
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/model.FullProduct'
      produces:
      - application/json
      responses:
        "201":
          description: Item criado com sucesso.
          schema:
            $ref: '#/definitions/model.FullProduct'
        "400":
          description: Requisição inválida.
          schema:
            type: string
        "500":
          description: Erro interno.
          schema:
            type: string
      tags:
      - Produtos
  /v1/product/{id}:
    get:
      description: Retorna um item com base no ID informado.
      operationId: GetProductById
      parameters:
      - description: ID do item
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Requisição bem sucedida.
          schema:
            $ref: '#/definitions/model.FullProduct'
        "404":
          description: Item não encontrado.
          schema:
            type: string
        "500":
          description: Erro interno.
          schema:
            type: string
      tags:
      - Produtos
  /v1/product/gtin/{gtin}:
    get:
      description: Retorna um item com base no GTIN informado.
      operationId: GetProductByGtin
      parameters:
      - description: GTIN do item
        in: path
        name: gtin
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Requisição bem sucedida.
          schema:
            $ref: '#/definitions/model.FullProduct'
        "404":
          description: Item não encontrado.
          schema:
            type: string
        "500":
          description: Erro interno.
          schema:
            type: string
      tags:
      - Produtos
swagger: "2.0"
